### ISSUE TITLE
Cannot read tx_bytes no tailscale interface found

### ISSUE THREAD

**Issue by Justinzobel** [f-koehler/KTailctl#27]
Errors in the terminal when started from there:
```
Cannot read tx_bytes
no tailscale interface found
```

But I have a tailscale0 interface showing in `ip a` and I am definitely connected to the tailscale network.

**Comment by f-koehler** [comment]
Interesting, I directly use the official tailscale code to determine the interface name. Can you tell me which version of tailscale you are running, i.e., what the ouput of `tailscale --version` is? Am I right to assume that you rune the latest flatpak from flathub?

**Comment by Justinzobel** [comment]
```
1.46.0
  tailscale commit: 03b5aa8b4d846b67e5f6e14543f5e8fd25ff259d
  other commit: ea91237a35098bf2e10af36cddde53bb96e7ad3c
  go version: go1.21rc3
  ```
  On Fedora 38

**Comment by Justinzobel** [comment]
Yes installed from flathub today.

**Comment by f-koehler** [comment]
@Justinzobel  Sorry no update yet, a bit short on time atm. But I set up a Fedora 38 VM and will try to reproduce this issue.

Does the rest of the interface work? This should only break the overall interface statistics.

**Comment by Justinzobel** [comment]
No problem at all. I haven't played much with the interface, I only installed it as someone mentioned it and I've been interested in a Tailscale GUI, but as far as I can see everything is listed correctly.

**Comment by f-koehler** [comment]
@Justinzobel Version 0.7.0 is available on flathub and should resolve this issue.

**Comment by perroboc** [comment]
Version 0.7.0 doesn't fix this issue :(

```console
➜  ~ flatpak info org.fkoehler.KTailctl  

KTailctl - A GUI for the Tailscale mesh network

          ID: org.fkoehler.KTailctl
         Ref: app/org.fkoehler.KTailctl/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.7.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 14.6 MB
     Runtime: org.kde.Platform/x86_64/5.15-22.08
         Sdk: org.kde.Sdk/x86_64/5.15-22.08

      Commit: 8c84f1943ceba50d24efe461ce5167824a9027981b91408a73ac0744fd858969
      Parent: cf6115cc1e40f8e2ade34de61195531bc64e9e85d02d998e3ae9bea1c5a24cc0
     Subject: Release v0.7.0. (0dcc5730)
        Date: 2023-08-01 02:23:22 +0000
➜  ~ flatpak run org.fkoehler.KTailctl
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "(c) 2023" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "GUI for tailscale on the KDE Plasma desktop" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: "@title"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Project Maintainer" msgid_plural: "" msgctxt: "@info:credit"
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Fabian K\xC3\xB6hler" msgid_plural: "" msgctxt: "@info:credit"
"/home/perro/Downloads/taildrop/" is not a directory
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Peers" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Quit" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "About KTailctl" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Settings" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Statistics" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "Peers" msgid_plural: "" msgctxt: ""
kf.i18n: KLocalizedString: Using an empty domain, fix the code. msgid: "KTailctl" msgid_plural: "" msgctxt: ""
Warning: client version "1.46.1-ERR-BuildInfo" != tailscaled server version "1.46.1-dev20230726-t2d3223f55-dirty"
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
no tailscale interface found
Cannot read tx_bytes
^C
➜  ~ tailscale --version
1.46.1-dev20230726
  tailscale commit: 2d3223f557924d408b5d67b80440d6fba264a0fd-dirty
  go version: go1.20.6
```

![image](https://github.com/f-koehler/KTailctl/assets/2722773/d81adb23-bf63-447a-9c4c-3efb7a988d35)

**Comment by f-koehler** [comment]
Seems I have fixed it in the meantime. Feel free to reopen if this issue still persists.
